language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libboost-dev

install:
  - CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz"
  - mkdir .local
  - travis_retry wget --no-check-certificate --quiet -O - $CMAKE_URL | tar --strip-components=1 -xz -C .local
  - export PATH=$TRAVIS_BUILD_DIR/.local/bin:$PATH

before_script:
  - mkdir build
  - cd build
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - export CXXFLAGS="--coverage"
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make
  - ctest --output-on-failure

after_script:
  - ../.coveralls
