language: cpp
sudo: false

install:
  - CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz"
  - mkdir .local
  - travis_retry wget --no-check-certificate --quiet -O - $CMAKE_URL | tar --strip-components=1 -xz -C .local
  - export PATH=$TRAVIS_BUILD_DIR/.local/bin:$PATH

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ctest --output-on-failure
